- terraform/aws/base-infra/outputs.tf
- terraform/aws/eks/infra.tf
- terraform/aws/eks/loadbalancer.tf
- terraform/aws/eks/outputs.tf
- terraform/aws/eks/security-groups.tf
- terraform/aws/eks/templates/cloud-config-base.yaml
- terraform/aws/eks/variables.tf
- terraform/config-params/control-center-post-config/gitlab.tf
- terraform/control-center/init/control-center-post-config/terragrunt.hcl
- terraform/gitlab/ci-templates/k8s-cluster/.gitlab/ci/Dockerfile
- terraform/gitops-base-config/generate-files/templates/keycloak/post-config/keycloak-ingress.yaml.tpl
- terraform/gitops-base-config/generate-files/templates/keycloak/post-config/keycloak-realm-cr.yaml.tpl
- terraform/gitops-base-config/generate-files/templates/mcm/kustomization.yaml.tpl
- terraform/gitops-base-config/generate-files/templates/mcm/values-mcm.yaml.tpl
- terraform/gitops-base-config/generate-files/templates/mcm/vault-certificate.yaml.tpl
- terraform/gitops-base-config/generate-files/templates/mojaloop/custom-resources/istio-gateway.yaml.tpl
- terraform/gitops-base-config/generate-files/templates/vault-pki-setup/vault-auth-config.yaml.tpl
- terraform/gitops-base-config/keycloak.tf
- terraform/gitops-base-config/mcm.tf
- terraform/gitops-base-config/mojaloop.tf
- terraform/k8s/ansible-k8s-deploy/terragrunt.hcl
- terraform/k8s/aws-vars.yaml
- terraform/k8s/common-vars.yaml
- terraform/k8s/gitops-build/terragrunt.hcl
- terraform/k8s/k8s-deploy/terragrunt.hcl
first draft module for eks cluster type
> first draft eks

- terraform/gitops/generate-files/templates/loki/chart/values.yaml.tpl
In this PR, we added 6  grafana opensource dashboards and 6 mojaloop dashboards.
> Added grafana dashboards

- terraform/gitops/generate-files/templates/mojaloop/istio-config.yaml.tpl
- terraform/gitops/generate-files/templates/mojaloop/values-finance-portal.yaml.tpl
- terraform/gitops/generate-files/templates/mojaloop/vault-secret.yaml.tpl
- terraform/gitops/generate-files/templates/ory/keycloak-realm-cr.yaml.tpl
- terraform/gitops/generate-files/templates/ory/values-bof.yaml.tpl
- terraform/gitops/generate-files/templates/ory/values-kratos-selfservice-ui-node.yaml.tpl
- terraform/gitops/generate-files/templates/ory/values-kratos.yaml.tpl
- terraform/gitops/generate-files/templates/ory/values-oathkeeper.yaml.tpl
- terraform/gitops/generate-files/templates/ory/vault-secret.yaml.tpl
- terraform/gitops/k8s-cluster-config/app-deploy.tf
- terraform/gitops/k8s-cluster-config/ory.tf
- terraform/gitops/mojaloop/mojaloop.tf
> fix: small changes

- terraform/gitops/generate-files/templates/mojaloop/rbac.yaml.tpl
> feat-iprod-386: fixed mr.permissions array

- terraform/gitops/generate-files/templates/mojaloop/rbac.yaml.tpl
feat-iprod-386: fixed templating
> feat-iprod-386: fixed templating

- terraform/gitops/generate-files/templates/mojaloop/rbac.yaml.tpl
- terraform/k8s/mojaloop-rbac-api-resources.yaml
> feat-iprod-386: fixed portal_fqdn interpolating

- terraform/ansible/k8s-deploy/ansible.tf
- terraform/ansible/k8s-deploy/variables.tf
- terraform/config-params/control-center-post-config/gitlab.tf
- terraform/control-center/init/control-center-post-config/terragrunt.hcl
- terraform/k8s/ansible-k8s-deploy/terragrunt.hcl
MR is for the below feature 
Invoke the k8s_cluster_destroy playbook using local-exec provisioner when destroy action gets invoked
> Feature cleanup netmaker envnodes

- terraform/gitops/generate-files/templates/mcm/istio-gateway.yaml.tpl
- terraform/gitops/generate-files/templates/mcm/values-mcm.yaml.tpl
- terraform/gitops/generate-files/templates/mojaloop/istio-config.yaml.tpl
- terraform/gitops/generate-files/templates/mojaloop/values-finance-portal.yaml.tpl
- terraform/gitops/generate-files/templates/pm4ml/istio-gateway.yaml.tpl
- terraform/gitops/generate-files/templates/pm4ml/values-pm4ml.yaml.tpl
- terraform/gitops/mojaloop/mcm.tf
- terraform/k8s/pm4ml-vars.yaml
merge after:
- https://github.com/pm4ml/helm/pull/31
- https://github.com/pm4ml/mojaloop-payment-manager-helm/pull/142
- PR for financial portal
> fix: kratos logout

- terraform/k8s/default-config/bare-metal-vars.yaml
- terraform/k8s/default-config/cluster-config.yaml
- terraform/k8s/default-config/pm4ml-vars.yaml
adding commented config in pm4ml and baremetal
> adding config changes

- terraform/gitops/generate-files/templates/monitoring/post-config/dashboards/k8s.yaml.tpl
Update for this https://github.com/mojaloop/helm/pull/610
> Update k8 dashboard ref

- terraform/gitops/generate-files/templates/monitoring/post-config/monitoring-crs.yaml.tpl
https://infitx-technologies.atlassian.net/browse/IPROD-482
references the changes in this PR: https://github.com/mojaloop/helm/pull/613
> [IPROD-482] Add kafka topic and cluster dashboards

- terraform/gitlab/ci-templates/bootstrap/.gitlab/scripts/seedenvproject.sh
- terraform/gitlab/ci-templates/k8s-cluster/.gitlab/scripts/config-merge.sh
- terraform/gitlab/ci-templates/k8s-cluster/.gitlab/scripts/dictmerge.py
- terraform/k8s/default-config/pm4ml-vars.yaml
- Config merge enhancements for pm4ml configs
- Include 'mojaloop-stateful-resources.json','common-stateful-resources.json','mojaloop-rbac-api-resources.yaml' in config merge
- Create custom-config/cluster-config.yaml file with deploy-env-templates
> Feature enhance config merge

- terraform/gitops/generate-files/templates/monitoring/install/kustomization.yaml.tpl
- terraform/gitops/generate-files/templates/monitoring/install/loki-secret.yaml
- terraform/gitops/generate-files/templates/monitoring/install/values-loki.yaml.tpl
- terraform/gitops/k8s-cluster-config/monitoring.tf
Move away from filesystem storage in loki and go towards more reliable storage
> Integrate minio with Loki

- terraform/gitops/generate-files/templates/storage/chart/values.yaml.tpl
see https://longhorn.io/docs/1.4.4/high-availability/data-locality/#data-locality-settings
> fix: use local storage by default

- terraform/gitops/generate-files/templates/pm4ml/istio-gateway.yaml.tpl
- terraform/gitops/pm4ml/pm4ml.tf
- authorisation policy name collision fix 
- ttk backend url fix
> Fix for auth and wrong backend

- terraform/k8s/default-config/mojaloop-vars.yaml
- terraform/k8s/default-config/pm4ml-vars.yaml
Correcting the pm4ml chart version and fspiop_ory flag
> Correcting the pm4ml chart version and fspiop_ory flag

- terraform/gitops/generate-files/templates/mojaloop/istio-config.yaml.tpl
- terraform/gitops/stateful-resources/stateful-resources-config.tf
- terraform/gitops/stateful-resources/templates/stateful-resources/strimzi/kafka/kafka-with-dual-role-nodes.yaml.tpl
- terraform/k8s/default-config/platform-stateful-resources.yaml
- add missing topics
- add missing fx paths
- topics converted to map, instead of array
- replaced repetitions with aliases and anchors
> fx provisioning and topics simplification

- profiles.md
- terraform/gitlab/ci-templates/bootstrap/.gitlab/scripts/seedenvproject.sh
- terraform/gitlab/ci-templates/k8s-cluster/.gitlab-ci.yml
- terraform/gitlab/ci-templates/k8s-cluster/.gitlab/scripts/config-merge.sh
- terraform/gitlab/ci-templates/k8s-cluster/.gitlab/scripts/dictmerge.py
- terraform/gitlab/ci-templates/k8s-cluster/.gitlab/scripts/refresh-repo.sh
- terraform/gitops/k8s-cluster-config/app-deploy.tf
- terraform/gitops/k8s-cluster-config/ory.tf
- this includes a change to convert pm4mls from array to map
- the configs "common-stateful-resources.json" , "mojaloop-stateful-resources.json" , "mojaloop-rbac-api-resources.yaml","vnext-stateful-resources.json" are not supported in profiles, due to array specific logic. They could be refactored to use maps, but some are likely to be removed
> feat: profiles

- terraform/k8s/default-config/platform-stateful-resources.yaml
https://infitx-technologies.atlassian.net/browse/CTO-182
> Port as 3307 to avoid the conflict in case of managed service

- profiles.md
- terraform/gitlab/ci-templates/k8s-cluster/.gitlab/scripts/refresh-repo.sh
- terraform/gitlab/ci-templates/k8s-cluster/.gitlab/scripts/submodule-update.sh
- terraform/k8s/gitops-build/terragrunt.hcl
- enable declarative control of submodules
- enable cluster-config vars to be reused in other config files
> feat: declarative submodules

- terraform/gitops/generate-files/templates/monitoring/post-config/alerts/node-alerts.yaml.tpl
- removed `HostFilesystemDeviceError` alert. See [here](https://infitx-technologies.atlassian.net/browse/CTO-308?focusedCommentId=10919)
-
> CTO-308: Remove HostFilesystemDeviceError alert

- terraform/gitops/generate-files/templates/mcm/values-mcm.yaml.tpl
- terraform/gitops/mojaloop/mojaloop.tf
- terraform/gitops/pm4ml/pm4ml.tf
- terraform/gitops/proxy-pm4ml/pm4ml.tf
- terraform/k8s/default-config/mojaloop-vars.yaml
- pass switchId to mcm
- allow usage of variables in override files
- add currency property in mojaloop var map
> pass switchId to mcm

- terraform/gitops/generate-files/templates/mcm/configmaps/vault-config-configmap.hcl.tpl
If fxpCurrencies is set, loop through them to onboard FXP for each currency. Observed the following for each currency:
> fxp provisioning

- terraform/gitops/generate-files/templates/mcm/configmaps/vault-config-configmap.hcl.tpl
- terraform/gitops/generate-files/templates/mojaloop/values-mojaloop.yaml.tpl
(cherry picked from commit 09c0eb9923752160b7d985340b843e505c815535)
> fix: provisioning paths

- terraform/gitops/generate-files/templates/mojaloop/values-mojaloop.yaml.tpl
(cherry picked from commit d106c5b3e6703fa7db46e847bf829f08d0dc0f34)
> fix: GP default env

- terraform/k8s/default-config/mojaloop-rbac-permissions.yaml
Added RBAC permission fields for the new added resource fields
> IME-153 new rbac permission fields

- terraform/aws/eks/infra.tf
> ami fix for eks

- terraform/aws/eks/infra.tf
- terraform/aws/eks/variables.tf
- terraform/ccnew/ansible-k8s-deploy/terragrunt.hcl
- terraform/ccnew/default-config/common-vars.yaml
- terraform/k8s/ansible-k8s-deploy/terragrunt.hcl
- terraform/k8s/default-config/common-vars.yaml
- Default to k8s 1.31 for microk8s and eks
- EKS AMI version update
> k8s version updates

- terraform/gitlab/ci-templates/k8s-cluster/.gitlab-ci.yml
- terraform/gitops/generate-files/templates/pm4ml/values-pm4ml.yaml.tpl
- terraform/gitops/pm4ml/pm4ml.tf
- terraform/k8s/addons/generate-apps.tf
- terraform/k8s/addons/terragrunt.hcl
- terraform/k8s/default-config/pm4ml-vars.yaml
- pass submodule revisions to addons
- pass Gitlab vars to addons
- do not process template files for addons, which are not active
- check full trigger conditions for refresh-deploy-infra
> feat: release tagging

- terraform/gitops/generate-files/templates/monitoring/install/values-tempo.yaml.tpl
see https://github.com/grafana/tempo/issues/3064
> fix: OOM and could not initialize processors: local blocks processor requires traces wal

- gitops/applications/base/monitoring-post-config/grafana-crs.yaml
- gitops/applications/base/monitoring-post-config/istio-crs.yaml
- gitops/applications/base/monitoring/values-kube-prometheus.yaml
- gitops/argo-apps/base/monitoring-post-config.yaml
- gitops/argo-apps/base/monitoring.yaml
- terraform/ccnew/ansible-k8s-deploy/templates/argoapps.yaml.tpl
- terraform/ccnew/default-config/common-vars.yaml
- terraform/gitops/generate-files/templates/monitoring/install/values-prom-operator.yaml.tpl
- terraform/gitops/generate-files/templates/monitoring/post-config/istio-crs.yaml.tpl
- terraform/gitops/generate-files/templates/monitoring/post-config/monitoring-crs.yaml.tpl
- terraform/gitops/k8s-cluster-config/monitoring.tf
- terraform/k8s/default-config/common-vars.yaml
- Make prometheus scrap interval configurable
- Remove hardcoded scrap interval for istio metrics
- Upgrade instil dashboards to latest
> Optimize prometheus scrap interval
