terraform/gitops/generate-files/templates/loki/chart/values.yaml.tpl

This PR adds following changes
- scrap targets for mysql exporters (3 mysql dbs)
- label for dashboard sidecar

Add mysql exporter targets in prometheus

---

terraform/gitlab/ci-templates/k8s-cluster/.gitlab/scripts/dictmerge.py

In custom_config/pm4ml-vars.yaml, if we pass the following values
```
core_connector_config:
enabled: true
env:
TEST1_ID: '0720'
TEST1_PREFIX: '00002893'
The value '0720' is passing to the generated helm values file correctly but the value '00002893' is being transformed as an integer without preceding zeros like 2893
```
Solution:
Added a custom dumper that works with yaml.dump function
Some explanation about this issue is here
https://github.com/yaml/pyyaml/issues/98#issuecomment-388021094
`A leading zero in YAML 1.1 indicates an octal number, which can only have digits 0-7`

fix: added custom dumper for pm4ml merge function

---

terraform/gitops/generate-files/templates/storage/chart/values.yaml.tpl
terraform/gitops/generate-files/templates/storage/custom-resources/longhorn-job.yaml.tpl

- Disables longhorn checks on minio for new backups
- Set the cron job to twice a day [once in 12 hours]

Polling freq and backup job freq

---

terraform/gitops/k8s-cluster-config/monitoring.tf
terraform/k8s/default-config/common-vars.yaml

We no longer need a huge PV for loki since we are using minio buckets for log retension.

reduce loki_ingester_pvc_size to 10Gi from 50Gi

---

terraform/gitops/generate-files/templates/monitoring/install/values-loki.yaml.tpl
terraform/gitops/generate-files/templates/monitoring/install/vault-minio-ext-secret.yaml.tpl
terraform/gitops/k8s-cluster-config/monitoring.tf

Using `minio_credentials_secret_name` was not communicating that this is only specific to loki.

renamed minio_credentials_secret_name to minio_loki_credentials_secret_name

---

terraform/gitops/generate-files/templates/consul/values.yaml.tpl

consul inject is used as a part of consul service mesh which we do not use.  disabling this injection as it can cause issues with:
deployment of all components will call the consul injector webhooks and the consul webhooks are dependent on consul running and consul is dependent on longhorn (pvc) to run so a infinite loop can get created:
longhorn pod on node where consul pvc is running needs to restart -> consul pvc not available -> consul not ready -> consul webhook service not ready (crashloopbackoff) -> longhorn pod can’t be provisioned because of failure to call consul webhook

rm consul inject

---

terraform/gitops/generate-files/templates/monitoring/install/values-loki.yaml.tpl

This PR updates memcache configs based on https://github.com/memcached/memcached/wiki/ConfiguringLokiExtstore
- We only updated `memory-limit` and `max-item-size`
- We did not add extended params related to external store. As of now, we keep all our cache in memory. 
- We do not change "aggressive" configs for memcache client in loki since memcache is completely RAM backed as of now.

IPROD-668: Update command and args of loki memcached

---

terraform/gitops/generate-files/templates/mojaloop/grafana.yaml.tpl
terraform/k8s/default-config/mojaloop-vars.yaml

- move quoting-service dashboard to mojaloop/helm
- use `grafana_dashboard_tag` variable to define dashboard-performance-troubleshooting

All mojaloop grafana dashboards use same git tag

---

terraform/aws/support-svcs/deploy-rds/infra.tf
terraform/k8s/default-config/cluster-config.yaml
terraform/k8s/managed-services/terragrunt.hcl

- added clustername as prefix to the names of managed rds resources.
- added config parameter to customise the cidr of managed services vpc.

Support more than one cluster with managed RDS

---

terraform/gitops/generate-files/templates/mcm/configmaps/vault-config-configmap.hcl.tpl
terraform/gitops/generate-files/templates/mojaloop/istio-config.yaml.tpl
terraform/gitops/generate-files/templates/vnext/istio-config.yaml.tpl

Similar to https://github.com/mojaloop/iac-modules/commit/ada488faf54dafde1d46a77267d61bf5644747bc let's stop using `connection.sni`, as it seems to be causing errors

fix: remove connection.sni

---

terraform/gitops/generate-files/templates/pm4ml/values-pm4ml.yaml.tpl
terraform/k8s/default-config/pm4ml-vars.yaml

Update Experience API versions to align with the latest release. Add CACHE_URL to experience API and remove it from the Payment Manager API.

IME-132 - Feature/deploy fx changes experience api

---

terraform/gitlab/ci-templates/k8s-cluster/.gitlab-ci.yml

This will run the `refresh-deploy-infra` job when the pipeline is triggered with a trigger token. This allows updates in the [continuous deployment profile](https://github.com/infitx-org/profile-cd) to trigger new deployments via the GitHub action in that profile.
As per the docs here https://docs.gitlab.com/ee/ci/triggers/#configure-cicd-jobs-to-run-in-triggered-pipelines
> Additionally, the $CI_PIPELINE_TRIGGERED predefined CI/CD variable is set to true in pipelines triggered with a pipeline trigger token.

feat: allow triggering for continuous deployment

---

docs/addons.md
terraform/gitlab/ci-templates/k8s-cluster/.gitlab/scripts/config-merge.sh
terraform/gitlab/ci-templates/k8s-cluster/.gitlab/scripts/dictmerge.py
terraform/k8s/addons/generate-apps.tf
terraform/k8s/addons/terragrunt.hcl

- Simplified way to install addons like redpanda by listing the addon repository in the `submodules.yaml` file and configuring them in the `custom-config` folder, while the defaults will be taken from the repository of the addon, instead of being replicated in the env.
- Allow default-config to be missing and only custom-config to be present. The `default-config` folder should not really exist in the env repo, as we are not supposed to edit the files in it.

feat: addons

---

terraform/k8s/default-config/mojaloop-values-override.yaml

NOTE: this requires:
- `account-lookup-service` >= v15.6.0-iso.13
- `central-ledger` >= v17.9.0-iso.5
- `quoting-service` >= v15.9.0-iso.17
- `transaction-request-service` >= v14.3.1
- `ml-api-adapter` >=  v14.2.0-iso.14

feat: configure liveness probe endpoint for ALS, CL, QS, transaction-request-service, ml-api-adapter

---

terraform/k8s/addons/generate-apps.tf

This will allow templates in the addons to include JSON/YAML via `indent(xxx, file(filename))` instead of embedding them inline and creating big and hard to manage templates, that need escaping, lack syntax highlight, etc.

feat: pass filename to addon templates

---

terraform/gitlab/ci-templates/k8s-cluster/.gitlab-ci.yml
terraform/gitlab/ci-templates/k8s-cluster/.gitlab/scripts/refresh-repo.sh
terraform/gitops/pm4ml/pm4ml.tf

- refresh-deploy-infra did not work well when there were no changes in iac and profiles
- sync-wave for PMs was creating unnecessary dependencies between their ability to sync

fix: improve refresh-deploy

---

terraform/gitops/generate-files/templates/mojaloop/values-mojaloop.yaml.tpl

As timeout handler needs to send error callbacks now, it needs https request mutation to be able to communicate using mTLS. **_infitx/CSI-1346_**

fix: istio sidecar for als timeout handler

---

terraform/gitops/generate-files/templates/monitoring/install/values-loki.yaml.tpl
terraform/gitops/k8s-cluster-config/monitoring.tf

This allows to configure promtail in the common-vars.yaml file, for example:
```yaml
promtail_kubernetes_sd_configs:
- role: pod
namespaces:
names:
- mojaloop
```
Sending only mojaloop logs leads to a substantial improvement of resource usage:

fix: update promtail configuration to use common var

---

terraform/gitops/pm4ml/tenancy_vault.tf
terraform/gitops/proxy-pm4ml/tenancy_vault.tf

Add the metadata required for the PushSecret to work
Ref: https://github.com/external-secrets/external-secrets/blob/593eb139990bc0deeb437dfffc8b4d46bcfeea4f/pkg/provider/vault/vault.go#L477

feat: add custom metadata for PushSecret to work

---

terraform/gitops/stateful-resources/templates/stateful-resources/percona/mysql/db-cluster.yaml.tpl

- Set the core dump to happen in the /tmp folder instead of the PVC
- Reduce the size of the core dump

fix: avoid PVC space consumed by MySQL core dump

---

terraform/gitops/generate-files/templates/keycloak/post-config/keycloak-cr.yaml.tpl

A recent test shows ~7 minute startup when initializing the schema, so we give it ~10 in this PR

fix: add startup probe to allow time for Keycloak schema initialization
